// <auto-generated />
using System;
using Backend.Infrastructure.Persistence.EFC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(CoursesOnlineDbContext))]
    [Migration("20260217130011_GenerateInitialTables")]
    partial class GenerateInitialTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWSEQUENTIALID())", "DF_Courses_Id");

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Courses_CreatedAtUtc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Courses_ModifiedAtUtc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Courses_Id");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Courses_Title");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courses_Title_NotEmpty", "LTRIM(RTRIM([Title])) <> ''");
                        });
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWSEQUENTIALID())", "DF_CourseEvents_Id");

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("CourseEventTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseEvents_CreatedAtUtc");

                    b.Property<DateTime>("EventDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseEvents_ModifiedAtUtc");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_CourseEvents_Id");

                    b.HasIndex("CourseEventTypeId");

                    b.HasIndex("CourseId", "EventDate")
                        .HasDatabaseName("IX_CourseEvents_CourseId_EventDate");

                    b.ToTable("CourseEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourseEvents_Price", "[Price] >= 0");

                            t.HasCheckConstraint("CK_CourseEvents_Seats", "[Seats] > 0");
                        });
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseEventTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_CourseEventTypes_Id");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("IX_CourseEventTypes_TypeName");

                    b.ToTable("CourseEventTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourseEventTypes_TypeName_NotEmpty", "LTRIM(RTRIM([TypeName])) <> ''");
                        });
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseRegistrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWSEQUENTIALID())", "DF_CourseRegistrations_Id");

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("CourseEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CourseRegistrationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseRegistrations_ModifiedAtUtc");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_CourseRegistrations_RegistrationDate");

                    b.HasKey("Id")
                        .HasName("PK_CourseRegistrations_Id");

                    b.HasIndex("CourseEventId");

                    b.HasIndex("CourseRegistrationStatusId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ParticipantId", "CourseEventId")
                        .IsUnique()
                        .HasDatabaseName("IX_CourseRegistrations_ParticipantId_CourseEventId");

                    b.ToTable("CourseRegistrations", (string)null);
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseRegistrationStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_CourseRegistrationStatuses_Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_CourseRegistrationStatuses_Name");

                    b.ToTable("CourseRegistrationStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Paid"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Refunded"
                        });
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.PaymentMethodEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_PaymentMethods_Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentMethods_Name");

                    b.ToTable("PaymentMethods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Card"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Invoice"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cash"
                        });
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.InPlaceLocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_InPlaceLocations_Id");

                    b.HasIndex("LocationId", "RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_InPlaceLocations_LocationId_RoomNumber");

                    b.ToTable("InPlaceLocations", (string)null);
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.InstructorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWSEQUENTIALID())", "DF_Instructors_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Instructors_Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Instructors_Name");

                    b.ToTable("Instructors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Instructors_Name_NotEmpty", "LTRIM(RTRIM([Name])) <> ''");
                        });
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.LocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Locations_Id");

                    b.HasIndex("PostalCode")
                        .HasDatabaseName("IX_Locations_PostalCode");

                    b.ToTable("Locations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Locations_PostalCode_NotEmpty", "LTRIM(RTRIM([PostalCode])) <> ''");
                        });
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.ParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWSEQUENTIALID())", "DF_Participants_Id");

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Participants_CreatedAtUtc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(SYSUTCDATETIME())", "DF_Participants_ModifiedAtUtc");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Participants_Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Participants_Email");

                    b.ToTable("Participants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Participants_Email_NotEmpty", "LTRIM(RTRIM([Email])) <> ''");
                        });
                });

            modelBuilder.Entity("CourseEventInstructors", b =>
                {
                    b.Property<Guid>("CourseEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseEventId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseEventInstructors", (string)null);
                });

            modelBuilder.Entity("InPlaceEventLocations", b =>
                {
                    b.Property<Guid>("CourseEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InPlaceLocationId")
                        .HasColumnType("int");

                    b.HasKey("CourseEventId", "InPlaceLocationId");

                    b.HasIndex("InPlaceLocationId");

                    b.ToTable("InPlaceEventLocations", (string)null);
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseEventEntity", b =>
                {
                    b.HasOne("Backend.Infrastructure.Persistence.Entities.CourseEventTypeEntity", "CourseEventType")
                        .WithMany("CourseEvents")
                        .HasForeignKey("CourseEventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Infrastructure.Persistence.Entities.CourseEntity", "Course")
                        .WithMany("CourseEvents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseEventType");
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseRegistrationEntity", b =>
                {
                    b.HasOne("Backend.Infrastructure.Persistence.Entities.CourseEventEntity", "CourseEvent")
                        .WithMany("Registrations")
                        .HasForeignKey("CourseEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Infrastructure.Persistence.Entities.CourseRegistrationStatusEntity", "CourseRegistrationStatus")
                        .WithMany()
                        .HasForeignKey("CourseRegistrationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Infrastructure.Persistence.Entities.PaymentMethodEntity", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Infrastructure.Persistence.Entities.ParticipantEntity", "Participant")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseEvent");

                    b.Navigation("CourseRegistrationStatus");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.InPlaceLocationEntity", b =>
                {
                    b.HasOne("Backend.Infrastructure.Persistence.Entities.LocationEntity", "Location")
                        .WithMany("InPlaceLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CourseEventInstructors", b =>
                {
                    b.HasOne("Backend.Infrastructure.Persistence.Entities.CourseEventEntity", null)
                        .WithMany()
                        .HasForeignKey("CourseEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Infrastructure.Persistence.Entities.InstructorEntity", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InPlaceEventLocations", b =>
                {
                    b.HasOne("Backend.Infrastructure.Persistence.Entities.CourseEventEntity", null)
                        .WithMany()
                        .HasForeignKey("CourseEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Infrastructure.Persistence.Entities.InPlaceLocationEntity", null)
                        .WithMany()
                        .HasForeignKey("InPlaceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseEntity", b =>
                {
                    b.Navigation("CourseEvents");
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseEventEntity", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.CourseEventTypeEntity", b =>
                {
                    b.Navigation("CourseEvents");
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.LocationEntity", b =>
                {
                    b.Navigation("InPlaceLocations");
                });

            modelBuilder.Entity("Backend.Infrastructure.Persistence.Entities.ParticipantEntity", b =>
                {
                    b.Navigation("CourseRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
